CREATE TABLE training_report (
    id INT,
    name VARCHAR(255),
    designation VARCHAR(255),
    personalNo INT,
    dateOfBirth DATE,
    instituteName VARCHAR(255),
    trainingPeriod VARCHAR(255),
    trainingType VARCHAR(255),
    qualification VARCHAR(255),
    trainingEvent VARCHAR(255),
    topicsCovered VARCHAR(255),
    topicsAssimilated VARCHAR(255),
    faculties VARCHAR(255),
    useful VARCHAR(255),
    objective VARCHAR(255),
    objectivesMet VARCHAR(255),
    knowledgeImproved VARCHAR(255),
    useInWork VARCHAR(255),
    noWhy VARCHAR(255),
    repeatCourses VARCHAR(255),
    graduationLevel VARCHAR(255),
    suggestionRemark VARCHAR(255),
    date DATE
);
