CREATE TABLE IMS_report (
    id INT,
    audit_number INT,
    audit_date DATE,
    section VARCHAR(255),
    team_leader VARCHAR(255),
    team_member1 VARCHAR(255),
    team_member2 VARCHAR(255),
    team_member3 VARCHAR(255),
    team_member4 VARCHAR(255),
    team_member5 VARCHAR(255),
    team_member6 VARCHAR(255),
    team_member7 VARCHAR(255),
    team_member8 VARCHAR(255),
    auditee_rep1 VARCHAR(255),
    auditee_rep2 VARCHAR(255),
    auditee_rep3 VARCHAR(255),
    auditee_rep4 VARCHAR(255),
    audited_areas VARCHAR(255),
    summary_result VARCHAR(255),
    audit_notes VARCHAR(255),
    audit_leader VARCHAR(255),
    audit_date_sign DATE,
    distribution VARCHAR(255)
);
