CREATE TABLE training_need (
    id INT,
    name VARCHAR(255),
    personal_no INT,
    designation VARCHAR(255),
    date_of_birth DATE,
    section VARCHAR(255),
    date_of_joining_service DATE,
    qualification VARCHAR(255),
    nature_of_present_job VARCHAR(255),
    course1 VARCHAR(255),
    course2 VARCHAR(255),
    course3 VARCHAR(255),
    training_area1 VARCHAR(255),
    training_area2 VARCHAR(255),
    training_area3 VARCHAR(255),
    knowledge_improve VARCHAR(3),
    technology_developments VARCHAR(3),
    self_developments VARCHAR(3),
    future_assignments VARCHAR(3),
    recommendation1 VARCHAR(255),
    recommendation2 VARCHAR(255),
    recommendation3 VARCHAR(255),
    recommendation4 VARCHAR(255),
    recommendation5 VARCHAR(255),
    recommendation6 VARCHAR(255)
);
